[package]
name = "dicedb-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
prost = "0.12"
prost-types = "0.12"
tonic = "0.12.3"
uuid = { version = "1.16.0", features = ["v4"] }

[build-dependencies]
tonic-build = "0.12.3"
